#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @export %@% %|% %||% eval_tidy quos set_names
#' @export all_of any_of contains ends_with everything last_col matches num_range starts_with where
#' @export as_labeller element_text ggplot labs theme_get theme_set theme_update
#' @export count mutate rename
#' @export fct_count fct_recode
#' @export list_rbind list_transpose map map2 map2_chr map_chr map_dbl map_int
#' @export str_to_title
#' @export tibble
#' @importFrom broom glance
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr count
#' @importFrom dplyr desc
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr select
#' @importFrom dplyr summarise
#' @importFrom dplyr transmute
#' @importFrom forcats fct_collapse
#' @importFrom forcats fct_count
#' @importFrom forcats fct_cross
#' @importFrom forcats fct_drop
#' @importFrom forcats fct_recode
#' @importFrom forcats fct_relevel
#' @importFrom forcats fct_reorder
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 as_labeller
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_col
#' @importFrom ggplot2 geom_errorbar
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labeller
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 margin
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 scale_y_reverse
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_get
#' @importFrom ggplot2 theme_set
#' @importFrom ggplot2 theme_update
#' @importFrom purrr imap
#' @importFrom purrr list_rbind
#' @importFrom purrr list_transpose
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_dbl
#' @importFrom purrr map_int
#' @importFrom purrr map_lgl
#' @importFrom purrr map2
#' @importFrom purrr map2_chr
#' @importFrom purrr walk
#' @importFrom rlang :=
#' @importFrom rlang .data
#' @importFrom rlang %@%
#' @importFrom rlang %@%<-
#' @importFrom rlang %|%
#' @importFrom rlang %||%
#' @importFrom rlang as_label
#' @importFrom rlang as_name
#' @importFrom rlang call2
#' @importFrom rlang check_dots_empty
#' @importFrom rlang data_sym
#' @importFrom rlang enexprs
#' @importFrom rlang enquo
#' @importFrom rlang enquos
#' @importFrom rlang eval_tidy
#' @importFrom rlang expr
#' @importFrom rlang exprs
#' @importFrom rlang f_rhs
#' @importFrom rlang f_rhs<-
#' @importFrom rlang get_expr
#' @importFrom rlang is_quosures
#' @importFrom rlang list2
#' @importFrom rlang new_formula
#' @importFrom rlang quo_get_env
#' @importFrom rlang quos
#' @importFrom rlang set_names
#' @importFrom rlang sym
#' @importFrom rlang syms
#' @importFrom stats add1
#' @importFrom stats AIC
#' @importFrom stats anova
#' @importFrom stats binomial
#' @importFrom stats C
#' @importFrom stats chisq.test
#' @importFrom stats coef
#' @importFrom stats confint
#' @importFrom stats contr.helmert
#' @importFrom stats contr.treatment
#' @importFrom stats contrasts
#' @importFrom stats contrasts<-
#' @importFrom stats family
#' @importFrom stats fisher.test
#' @importFrom stats formula
#' @importFrom stats glm
#' @importFrom stats predict.lm
#' @importFrom stats prop.test
#' @importFrom stats pt
#' @importFrom stats qt
#' @importFrom stats rbinom
#' @importFrom stats setNames
#' @importFrom stats weights
#' @importFrom stringr str_detect
#' @importFrom stringr str_locate
#' @importFrom stringr str_split
#' @importFrom stringr str_sub
#' @importFrom stringr str_to_title
#' @importFrom stringr str_trim
#' @importFrom tibble as_tibble
#' @importFrom tibble column_to_rownames
#' @importFrom tibble is_tibble
#' @importFrom tibble rownames_to_column
#' @importFrom tibble tibble
#' @importFrom tidyr pivot_wider
#' @importFrom tidyselect all_of
#' @importFrom tidyselect any_of
#' @importFrom tidyselect contains
#' @importFrom tidyselect ends_with
#' @importFrom tidyselect eval_select
#' @importFrom tidyselect everything
#' @importFrom tidyselect last_col
#' @importFrom tidyselect matches
#' @importFrom tidyselect num_range
#' @importFrom tidyselect starts_with
#' @importFrom tidyselect where
## usethis namespace: end
NULL
